Fixed pipeline

diff --git a/.github/workflows/unit_tests.yaml b/.github/workflows/unit_tests.yaml
--- a/.github/workflows/unit_tests.yaml
+++ b/.github/workflows/unit_tests.yaml
@@ -48,11 +48,17 @@ jobs:
           timestamp=$(date '+%Y-%m-%d_%H-%M-%S')
           mkdir -p test_results
           log_file="test_results/${timestamp}_report.log"
-          echo -e "\nTest Cases Report Report\n" >> $log_file
+          echo -e "\nTest Cases Report\n" >> $log_file
           # Run the tests and append output to the log file
           python -m coverage run --source=src -m unittest discover -s tests/unit_tests >> $log_file 2>&1
           echo -e "\nCoverage Report\n" >> $log_file
           coverage report >> $log_file
+
+          # Check exit code of the tests
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Please check the log file for more details."
+            exit 1
+          fi
 
       - name: Check coverage
         run: |
